apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ckv8tk9jz-dotnet-basic
  janus-idp.io/tekton: ckv8tk9jz-dotnet-basic
  backstage.io/kubernetes-id: ckv8tk9jz-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ckv8tk9jz-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
